baseURL = "//www.lrenazhou.com/"
languageCode = "en-us"
title = "lrenazhou"
theme = "hugo-theme-cactus"
copyright = "Lucy Zhou"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "About"
url = "/"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white"
  rss = true # generate rss feed. default value is false

  # Home page settings
  description = "Lucy Zhou (they/she) is a writer based in the Bay Area. Their writing has appeared in Nat. Brut, The Offing, X-R-A-Y Literary Magazine, and has been nominated for a Pushchart Prize. In 2020, they received an honorable mention for the Felicia Farr Lemmon Poetry Prize from the Academy of American Poets. They are a 2023 PEN Emerging Voices fiction fellow. Catch them curled up next to Astrid, their long-haired cat, while endlessly revising their pieces."

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/lrzhou/"
  [[params.social]]
    name = "instagram"
    link = "https://www.instagram.com/lrenazhou/"
  [[params.social]]
  	name = "font-awesome"
  	link = "https://letterboxd.com/lrzhou1010/"
  [[params.social]]
    name = "email"
    link = "lrzhou1010@gmail.com"
